name: Hello, World!

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Echo "Hello, Neeraj!"
        run: echo "Hello, Neeraj!"
